### ISSUE TITLE
Flawed hash methods

### ISSUE THREAD

**Issue by jebeld17** [cj123/go-ipsw#1]
With MD5 and SHA1 both being proven as unsafe methods of verification, I would suggest adding SHA256 (and up) support available on the ipsw.me site for the main supported hash method.
SHA256 is the new standard, and is much more reliable.
![capture](https://user-images.githubusercontent.com/9492083/29242515-dba7c7ea-7f5c-11e7-88db-ffe4a3d3a98f.PNG)

[Secure Hash Methods](https://en.wikipedia.org/wiki/Secure_Hash_Algorithms)

**Comment by cj123** [comment]
Hi, I'm aware of newer more secure hashing methods, however:

1) Hashes come directly from Apple, they are not computed by ipsw.me in any way.
2) Doing this would require a large amount of bandwidth on my part, downloading (as it currently stands) 1933 IPSWs (3.2 TB worth) and far more OTA zips. 

If at some point Apple do publish SHA256 hashes for IPSWs, then I'll be sure to include them on the site. 

For now, I find it hard to believe someone could create a malicious IPSW file which a) matches the hash of an existing one and b) restores successfully (or causes other issues with malicious intent).
